REPO_TAGLINE: Object-oriented programming • design • abstraction
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: peace
SITE_URL: https://academic-codex.github.io/SCE0610-Programacao-Orientada-a-Objetos

BG_1: "#0C4A6E"
BG_2: "#075985"
TEXT_MAIN: "#F0F9FF"
TEXT_MUTED: "#BAE6FD"
ACCENT: "#38BDF8"
CARD_RADIUS: "18"